### ISSUE TITLE
http://thatcamp.org/docs/logos/ does not load

### ISSUE THREAD

**Issue by terrainsvagues** [chnm/thatcamp-org#122]
Results in ERR_CONNECTION_TIMED_OUT

**Comment by amandafrench** [comment]
So sorry this has taken me so long, @terrainsvagues! We moved servers and the new one didn't allow listing the contents of the folder. I've changed the links so that they point directly at the files: you can download .psd and .png logo files for the various themes at http://thatcamp.org/docs/logos.zip
