### ISSUE TITLE
New users registering with THATCamp Registrations don't get Activate or login info email

### ISSUE THREAD

**Issue by amandafrench** [chnm/thatcamp-org#124]
When users register on a THATCamp site using @clioweb's THATCamp Registrations plugin, they don't receive any email that lets them activate their user account or set their password. 

Some notes: 

* People who register themselves at thatcamp.org do get an "Activate account" email
![screenshot 2016-03-23 12 56 43](https://cloud.githubusercontent.com/assets/227453/14019646/3caa4dde-f1aa-11e5-832c-e3231b99e469.png)

* Existing users who register themselves on a subsite with THATCamp Registrations do get a reminder email about their username that includes the password reset link
![screenshot 2016-03-23 12 49 40](https://cloud.githubusercontent.com/assets/227453/14019690/72519046-f1aa-11e5-982d-f1d94641218f.png)

* The "Pending, Accepted, Rejected" emails defined in THATCamp Registrations Settings do get sent just fine. The users also do get created just fine. 

See issue at http://thatcamp.org/forums/topic/log-in-info-not-sent/#post-5433 

I have a feeling that this has been an issue for awhile, and that hapless THATCampers have just been "resetting" their passwords with the Lost Password link as described in the default text for the "Approved Registration" email in THATCamp Registrations Settings. 

Would be great if you could take a look, @boonebgorges, but I'm also pinging @clioweb since he wrote it ... let me know if it's a Reclaim issue instead, of course.

**Comment by timmmmyboy** [comment]
Just in case it's relevant to this at all, we currently have all mail routed via Mandrill (may be switching to another transactional email service since they're going to push Mandrill to paid Mailchimp plans but that's neither here nor there). The server should still respect any regular email calls though, we're basically just doing the routing via Postfix to use an external service for deliverability.

**Comment by amandafrench** [comment]
What the what, @timmmmyboy, I didn't even ping you. :) Oh, right, I forgot we added you as a member of this repo. But yes: I suspect it's a code issue, not an email sending issues, as described above. Thanks!

**Comment by amandafrench** [comment]
Y'alls customer service mojo continues to amaze me, @timmmmyboy. :+1:

**Comment by boonebgorges** [comment]
At a glance, registration should work like this https://github.com/chnm/thatcamp-org/blob/master/wp-content/plugins/thatcamp-registrations/thatcamp-registrations-functions.php#L260

Registratation is saved in the database on line 270, email triggered on 281 and then fired at 678 https://github.com/chnm/thatcamp-org/blob/610e7e3361a1a4ec9e489b05b7e9ba4a24572d92/wp-content/plugins/thatcamp-registrations/thatcamp-registrations-functions.php#L657 So whatever is going wrong must be between these lines. 

I will be better able to debug this if I'm able to get a reasonable clone of thatcamp.org on my local machine. @timmmmyboy it looks like my SSH key is no longer valid on thatcamp.org. Can you re-add it? I will send it to you if you don't have it anymore.

**Comment by timmmmyboy** [comment]
@boonebgorges Make sure you're logging in as user thatcamp. I see an ssh key in there unless it's changed. Email me with what you have if it's not working.

**Comment by amandafrench** [comment]
Thanks, @boonebgorges! But the emails triggered at line 657 are all being sent properly: those are the ones that are defined by the plugin. I can't quite tell at line 260 if there's some kind of "new user notification" email being sent or not, but what's needed is something like https://codex.wordpress.org/Function_Reference/wp_new_user_notification  .

**Comment by amandafrench** [comment]
Also, sad to say, I've gotten sloppy about keeping GitHub and production in sync, and we don't have access to a development server anymore. I'll see if I can push changes to this repo from production.

**Comment by boonebgorges** [comment]
@timmmmyboy Ah, `-l thatcamp` worked. Thanks!

@amandafrench If you can possibly sync the repo so it's back up to date - at least the custom bits (thatcamp-karma and thatcamp-registrations and anything in mu-plugins) it would be helpful, though probably not critical for this purpose.

>  I can't quite tell at line 260 if there's some kind of "new user notification" email being sent or not, but what's needed is something like https://codex.wordpress.org/Function_Reference/wp_new_user_notification . 

Ah, I see. It looks like the plugin tries to send the notification after the user has been approved. See https://github.com/chnm/thatcamp-org/blob/610e7e3361a1a4ec9e489b05b7e9ba4a24572d92/wp-content/plugins/thatcamp-registrations/thatcamp-registrations-functions.php#L444 But this will only happen when the registration is approved, because it's not until that moment that the WP user is created. If you need the email at the time of registration, we either (a) rewrite the plugin so that it creates users earlier (lots of work), or (b) fake our own version of `wp_new_user_notification()`. Am I understanding the issue correctly?

**Comment by amandafrench** [comment]
Yes, pretty much! Except we don't need the email at the time of registration, we need it after the registration is approved and the WP user is created. There *is* an email sent when the registration is approved, but it basically just says "Your registration is approved." So people don't know how to log in. 

Am syncing the repo now ...

**Comment by amandafrench** [comment]
Sorry, the keychain passphrase I could swear is the right one doesn't work: might have to generate a new key ... working on it!

**Comment by amandafrench** [comment]
Got my passphrase but am wreaking massive git destruction. :) Will untangle it all as best I can soon.

**Comment by amandafrench** [comment]
Okay, @boonebgorges, production thatcamp.org and the master branch of this repo are now synched up, although I think I'll have to recreate some things later that I've saved on other branches (mostly plugin updates). Will do better from now on. 

I'll test to make sure that the issue still persists on this version of prod thatcamp.org, as well.

**Comment by amandafrench** [comment]
And to clarify, https://github.com/chnm/thatcamp-org/blob/610e7e3361a1a4ec9e489b05b7e9ba4a24572d92/wp-content/plugins/thatcamp-registrations/thatcamp-registrations-functions.php#L444 looks to me like exactly the function that doesn't seem to be, well, functioning. It can and should happen after the registration is approved and a new user created, but doesn't appear to be. Happening.

**Comment by amandafrench** [comment]
Yep, issue persists. No welcome email sent to new users who use the THATCamp Registration plugin. Found this possibly pertinent thread: https://wordpress.org/support/topic/welcome-emails-not-sending-wp-431 -- wonder if just updating WP core would help.

**Comment by boonebgorges** [comment]
> wonder if just updating WP core would help

Yup, it would have helped. I managed to track it down to the issue described here https://core.trac.wordpress.org/ticket/34377, which was fixed in 4.4. 

I've also put a fix in 7cc4cf9 that does not depend on WP 4.4. It's live on the server (in a dirty index, because I don't have the SSH passphrase to pull to the server) and also in 7cc4cf9.

While looking at this, I cleared up a bunch of PHP notices in the codebase, which should explain the last dozen changesets in the master branch.

**Comment by amandafrench** [comment]
Hooray, wonderful, thanks! And I've cleaned up the dirty index on production THATCamp, too, so it's all in sync with this repo. I'm going to go update some plugins and, perhaps, WP core. And I think maybe I'll even set up a development instance on my own personal server, because why the heck not. Again, thanks, @boonebgorges.

**Comment by boonebgorges** [comment]
Whoop!
